workspace("gta4")
  configurations({"Debug","Release"})
  platforms({"Mac"})
  location("build")
project_root = "../.."
project("gta4")
  uuid("12345678-abcd-ef01-2345-6789abcdef01")
  kind("ConsoleApp")
  language("C++")
  cppdialect("C++17")
  targetname("gta4")
  defines({"XENIA_STATIC_RECOMP=1","PPC_IMAGE_BASE=0x82000000ull","PPC_IMAGE_SIZE=0x11F0000ull","PPC_CODE_BASE=0x82120000ull","PPC_CODE_SIZE=0x8F3D5Cull"})
  includedirs({project_root.."/third_party/simde/simde","."})
  files({"main.cpp","ppc_func_mapping.cpp","ppc_recomp.*.cpp","kernel_impl.cpp"})
  filter("platforms:Mac")
    links({"pthread"})
  filter("toolset:clang or toolset:gcc")
    buildoptions({"-Wno-unused-variable","-Wno-unused-but-set-variable"})
  filter({})
